# Generated by Django 2.2.7 on 2019-11-18 02:59

from django.db import migrations, models
import foundations.models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='serial_no',
            field=models.UUIDField(default=foundations.models.get_next, editable=False, primary_key=True, serialize=False),
        ),
    ]
