# Generated by Django 2.2.7 on 2019-11-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0002_airqualitydb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airqualitydb',
            old_name='sensor_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='airqualitydb',
            name='value',
            field=models.IntegerField(),
        ),
    ]
