# Generated by Django 2.2.7 on 2019-11-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0003_auto_20191115_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='id',
        ),
        migrations.AddField(
            model_name='instrument',
            name='serial_no',
            field=models.AutoField(default=1212, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
